name: npm-publish

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: shawnbot/npm-publish-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # NOTE: use the NODE_ prefix instead of NPM_ here!
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_GROUP }}
        token: ${{ secrets.TG_BOT_TOKEN }}
        format: markdown
        message: |
          📌 **Версия Kalium19 ${{ steps.publish.outputs.version }} опубликована в npm!**
          👨‍💻 [${{ github.actor }}](https://github.com/${{ github.actor }}) / telegram: @${{ github.actor }}
          🗂 [${{ github.repository }}](https://github.com/${{ github.repository }})
          #️⃣ [${{github.sha}}](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          🤖 ${{github.workflow}}